### ISSUE TITLE
pyfloat requires a range of at least 1

### ISSUE THREAD

**Issue by Tenzer** [joke2k/faker#1390]
* Faker version: 5.7.0
* OS: Linux (Docker container)

pyfloat cannot work with ranges less than 1 apart.

### Steps to reproduce

```py
>>> from faker import Faker
>>> Faker().pyfloat(min_value=0.0, max_value=0.1)
```

### Expected behavior

An float with a value between 0.0 and 0.1 should be generated.

### Actual behavior

I get this exception:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    Faker().pyfloat(min_value=0.0, max_value=0.1)
  File "/usr/local/lib/python3.9/site-packages/faker/providers/python/__init__.py", line 83, in pyfloat
    left_number = self._safe_random_int(
  File "/usr/local/lib/python3.9/site-packages/faker/providers/python/__init__.py", line 106, in _safe_random_int
    return self.random_int(min_value, max_value - 1)
  File "/usr/local/lib/python3.9/site-packages/faker/providers/__init__.py", line 115, in random_int
    return self.generator.random.randrange(min, max + 1, step)
  File "/usr/local/lib/python3.9/random.py", line 311, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
```

**Comment by sciencectn** [comment]
See #1068

**Comment by Tenzer** [comment]
Ah, you're right. It's the same issue. I'll close this one then.
