### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by axychavan** [joke2k/faker#1449]
```python
Traceback (most recent call last):
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\com\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Bank Locker\mySite.py", line 39, in camera
    print("\n[INFO] Loading facial landmark predictor...")
OSError: [Errno 22] Invalid argument
```

Please help me resolve this issue.

**Comment by fcurella** [comment]
Hello @axychavan ,

I'm sorry, but I'm not seeing anything in your Traceback that relates  to this library. All I'm seeing is references to `flask`

**Comment by axychavan** [comment]
> Hello @axychavan ,
> 
> I'm sorry, but I'm not seeing anything in your Traceback that relates  to this library. All I'm seeing is references to `flask`

what should I share. I am sorry I am a newbie. please suggest

**Comment by fcurella** [comment]
If you're using Faker, can I see how you're calling it?

**Comment by axychavan** [comment]
can you send me your mail id I'll share the full project code

**Comment by fcurella** [comment]
@axychavan if you have a repository published, I could try to take a quick look.

**Comment by axychavan** [comment]
> @axychavan if you have a repository published, I could try to take a quick look.

bro error got solved. thanks
