### ISSUE TITLE
New Locale issue

### ISSUE THREAD

**Issue by sevdimali** [joke2k/faker#1469]
* Faker version: 8.8.2
* OS: Windows

Brief summary of the issue goes here.

I want to add az_AZ locale support to faker. I just created a new lorem provider with az_AZ. But when trying to test it. It gave an error like the below:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\sevdimali.isayev\Desktop\projects\sevdimalime\venv\lib\site-packages\faker\proxy.py", line 61, in __init__
    self._factory_map[locale] = Factory.create(locale, providers, generator, includes,
  File "C:\Users\sevdimali.isayev\Desktop\projects\sevdimalime\venv\lib\site-packages\faker\factory.py", line 42, in create
    raise AttributeError(msg)
AttributeError: Invalid configuration for faker locale `az_AZ`
```
Do I miss something?

**Comment by prescod** [comment]
Perhaps you should make a Pull Request so we can see your code.

**Comment by sevdimali** [comment]
it solved thanks.
