### ISSUE TITLE
Missing docstrings for the Faker and BaseProvider classes

### ISSUE THREAD

**Issue by omri374** [joke2k/faker#1522]
Hi, first of all, thanks for all the work on this amazing package!

I'm working on an extension to Faker (could be added as a contribution if you're interested) so I had to go deeper into the Faker code. While the code is very well written and performant, I found it difficult to understand the interfaces of the different objects. 
For example, the `Faker` class receives a list of objects which aren't specified in docstrings or type hints, making it difficult to understand how to use it, extend it or modify it.

For example, the inputs `includes` and `use_weighting` are not specified in the docs, docstrings or type hints. It would be great if you could add some context into what the constructor expects here. I would be happy to do a PR with type hints, docstring or doc changes.

Thanks!

**Comment by fcurella** [comment]
Thank you @omri374 ! I would really appreciate PRs about docs and type hints (where they are possible)

**Comment by omri374** [comment]
Sure, could you please provide a high level description of these parameters here? I will turn those into docstrings or type hints.

**Comment by omri374** [comment]
Hi @fcurella I'm on it. 
My only question is about `includes`, which is an input for both the `Faker` class and the `Factory` class. These `includes` are added to the list of providers. How are they different from providers?

**Comment by omri374** [comment]
Not sure if that's a local bug, but passing providers as arguments doesn't work:

```python
from faker.providers import BaseProvider

# create new provider class
class MyProvider(BaseProvider):
    def foo(self):
        return 'bar'

faker = Faker(providers = [MyProvider])
faker.foo()

```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/faker/faker/proxy.py", line 80, in __init__
    self._factory_map[locale] = Factory.create(
  File "/workspaces/faker/faker/factory.py", line 56, in create
    prov_cls, lang_found = cls._get_provider_class(prov_name, locale)
  File "/workspaces/faker/faker/factory.py", line 68, in _get_provider_class
    provider_class = cls._find_provider_class(provider, locale)
  File "/workspaces/faker/faker/factory.py", line 90, in _find_provider_class
    provider_module = import_module(provider_path)
  File "/opt/python/3.8.12/lib/python3.8/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: type object 'MyProvider' has no attribute 'startswith'
```
