### ISSUE TITLE
randrange complains about non-integer value when calling pyfloat.

### ISSUE THREAD

**Issue by 0xffea** [joke2k/faker#1538]
* Faker version: 9.2.0
* OS: Debian

randrange complains about non-integer value when calling pyfloat.

https://docs.python.org/3.10/whatsnew/3.10.html
> Non-integer arguments to random.randrange() are deprecated. The ValueError is deprecated in favor of a TypeError. >><
> (Contributed by Serhiy Storchaka and Raymond Hettinger in bpo-37319.)

### Steps to reproduce
```
import faker
fake=faker.Faker()
fake.pyfloat(min_value=0.1)
```
### Expected behavior

pyfloat returns a random float >0.1

### Actual behavior

```
Successfully installed faker-9.2.0
# python
Python 3.10.0 (default, Oct  6 2021, 00:03:11) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
>>> fake=faker.Faker()
>>> fake.pyfloat(min_value=0.1)
/usr/local/lib/python3.10/site-packages/faker/providers/__init__.py:115: DeprecationWarning: randrange() will raise TypeError in the future
  return self.generator.random.randrange(min, max + 1, step)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/faker/providers/python/__init__.py", line 110, in pyfloat
    left_number = self._safe_random_int(
  File "/usr/local/lib/python3.10/site-packages/faker/providers/python/__init__.py", line 147, in _safe_random_int
    return self.random_int(min_value, max_value - 1)
  File "/usr/local/lib/python3.10/site-packages/faker/providers/__init__.py", line 115, in random_int
    return self.generator.random.randrange(min, max + 1, step)
  File "/usr/local/lib/python3.10/random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
```

**Comment by ozeranskiy** [comment]
If we want `fake.pyfloat(min_value=0.1)` to return a random `float >0.1`, then conversion to int will not return the expected value.

**Comment by fcurella** [comment]
Closed in https://github.com/joke2k/faker/pull/1614
