### ISSUE TITLE
Unique profile

### ISSUE THREAD

**Issue by azmeuk** [joke2k/faker#1817]
* Faker version: 17.4.0
* OS: Archlinux

Data unicity and profile are two great faker features, bun unfortunately they don't fit well together:

```python
>>> import faker
>>> fake = faker.Faker()
>>> fake.unique.profile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/faker/proxy.py", line 314, in wrapper
    if retval not in generated:
TypeError: unhashable type: 'dict'
```

I suggest implementing unique profile generation, where each value in the profile would be unique.

**Comment by azmeuk** [comment]
Please stale bot, let this ticket open.

**Comment by azmeuk** [comment]
This issue is still relevant.

**Comment by azmeuk** [comment]
I still don't agree 😮‍💨

**Comment by azmeuk** [comment]
Yes I know that :) But in the meantime there is no reason to close the ticket.

**Comment by stefan6419846** [comment]
I personally do not like the stale bot stuff either, especially with low activity on maintainer tagging, but I am just a contributor here as well and not going to blame anyone for using it - there usually are perfectly valid reasons to introduce such bots.

**Comment by azmeuk** [comment]
I still wish to keep the ticket open.

**Comment by jayqi** [comment]
I've run into a similar error when trying to use the `words` provider. The uniqueness check doesn't handle providers that return unhashable containers. 

```python
from faker import Faker

fake = Faker()

fake.unique.words(nb=2)
#> Traceback (most recent call last):
#>   File "<string>", line 1, in <module>
#>   File "/Users/jqi/Downloads/faker-reprex/.venv/lib/python3.12/site-packages/faker/proxy.py", line 337, in wrapper
#>     if retval not in generated:
#>        ^^^^^^^^^^^^^^^^^^^^^^^
#> TypeError: unhashable type: 'list'
```

<sup>Created at 2024-07-25 00:17:25 EDT by [reprexlite](https://github.com/jayqi/reprexlite) v0.5.0</sup>
