### ISSUE TITLE
Unicity and localization

### ISSUE THREAD

**Issue by azmeuk** [joke2k/faker#1818]
* Faker version: 17.4.0
* OS: Archlinux

It seems that uniqueness and localization cannot be used together:

```python
>>> from faker import Faker
... fake = Faker(['it_IT', 'en_US', 'ja_JP'])
>>> fake['it_IT'].name()
'Giuseppina Juvara'
>>> fake['it_IT'].unique.name()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'unique'

>>> fake.unique.name()
'石井 翔太'
>>> fake.unique['it_IT'].name()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'UniqueProxy' object is not subscriptable
```

I would lo to be able to use both features at the same time!

**Comment by azmeuk** [comment]
Please stale bot, let this ticket open.

**Comment by azmeuk** [comment]
This issue is still relevant.

**Comment by stefan6419846** [comment]
Feel free to propose a corresponding PR.
