### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 100: ordinal not in range(128)

### ISSUE THREAD

**Issue by pedro-teixeira** [joke2k/faker#200]
I'm having problems to install Faker `0.4.2` on Python `3.4.2`:

```
$ pip install fake-factory
Collecting fake-factory
  Using cached fake-factory-0.4.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/98/hxvgjtd93ql1s1c4695y6w2h0000gq/T/pip-build-e5pfmuys/fake-factory/setup.py", line 9, in <module>
        NEWS = open(os.path.join(here, 'CHANGELOG.rst')).read()
      File "/Users/pedro.teixeira/.virtualenvs/cave/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 100: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/98/hxvgjtd93ql1s1c4695y6w2h0000gq/T/pip-build-e5pfmuys/fake-factory/setup.py", line 9, in <module>

        NEWS = open(os.path.join(here, 'CHANGELOG.rst')).read()

      File "/Users/pedro.teixeira/.virtualenvs/cave/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode

        return codecs.ascii_decode(input, self.errors)[0]

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 100: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/98/hxvgjtd93ql1s1c4695y6w2h0000gq/T/pip-build-e5pfmuys/fake-factory
```

**Comment by fcurella** [comment]
Hi @pedro-teixeira 

I suspect this has already been fixed in master. Can you try running `pip install https://codeload.github.com/joke2k/faker/zip/master` ?

**Comment by pedro-teixeira** [comment]
Thanks @fcurella, it works on master.

I'm looking forward for the release of `0.4.3`
