### ISSUE TITLE
setup.py cannot load under Python 3 when run with LC_ALL=C

### ISSUE THREAD

**Issue by DRMacIver** [joke2k/faker#242]
```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-75nsmtd3/fake-factory/setup.py", line 9, in <module>
NEWS = open(os.path.join(here, 'CHANGELOG.rst')).read()
File "/home/travis/build/DRMacIver/hypothesis/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 100: ordinal not in range(128)
```

Basically, you need to open this with an encoding parameter, as it's non-ascii. In order to make this work across Python 2 and 3 you probably want [io.open](https://docs.python.org/2/library/io.html#io.open).

**Comment by DRMacIver** [comment]
Ah, I beg your pardon. I see this is fixed in the latest version (which I didn't notice, because I still can't use it until you ship a version [that actually works correctly](https://github.com/joke2k/faker/pull/204))
