### ISSUE TITLE
pip install fails with    ImportError: No module named 'data'

### ISSUE THREAD

**Issue by bhanuvrat** [joke2k/faker#273]
traceback >>

    $ pip install faker
    Collecting faker
      Downloading Faker-0.0.4.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/var/folders/wm/sg5qm50s3tz4l0_pdgnrtqvw0000gn/T/pip-build-qzt74ti6/faker/setup.py", line 5, in <module>
            import faker
          File "/private/var/folders/wm/sg5qm50s3tz4l0_pdgnrtqvw0000gn/T/pip-build-qzt74ti6/faker/faker/__init__.py", line 11, in <module>
            import data
        ImportError: No module named 'data'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wm/sg5qm50s3tz4l0_pdgnrtqvw0000gn/T/pip-build-qzt74ti6/faker

**Comment by bhanuvrat** [comment]
oops, its called fake-factory .. and not faker on pip ... 
feel stupid. closing the issue.
