### ISSUE TITLE
Tests fail for current release

### ISSUE THREAD

**Issue by cbaines** [joke2k/faker#315]
As of the current release (v0.5.3), the tests fail. This has been fixed in master, but it would be convenient for me to have a recent release (the tests fail on the 0.5.2 and 0.5.1 releases also) for which the tests pass.

Could you make a release with these fixes included?

```
....E.E.....................
======================================================================
ERROR: test_date_time_this_period (faker.tests.FactoryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "faker/tests/__init__.py", line 344, in test_date_time_this_period
    self.assertTrue(self._datetime_to_time(provider.date_time_this_month(after_now=False)) <= self._datetime_to_time(datetime.datetime.now()))
  File "faker/providers/date_time/__init__.py", line 439, in date_time_this_month
    next_month_start = datetime(now.year, now.month + 1 % 12, 1)
ValueError: month must be in 1..12

======================================================================
ERROR: test_documentor (faker.tests.FactoryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "faker/tests/__init__.py", line 213, in test_documentor
    print_doc(output=output)
  File "faker/cli.py", line 89, in print_doc
    formatters = doc.get_formatters(with_args=True, with_defaults=True)
  File "faker/documentor.py", line 32, in get_formatters
    (provider, self.get_provider_formatters(provider, **kwargs))
  File "faker/documentor.py", line 87, in get_provider_formatters
    example = self.generator.format(name)
  File "faker/generator.py", line 62, in format
    return self.get_formatter(formatter)(*args, **kwargs)
  File "faker/providers/date_time/__init__.py", line 439, in date_time_this_month
    next_month_start = datetime(now.year, now.month + 1 % 12, 1)
ValueError: month must be in 1..12

----------------------------------------------------------------------
Ran 28 tests in 0.104s

FAILED (errors=2)
```

**Comment by joke2k** [comment]
Hi, thank you for report.

I'm investigating the cause of this error, can you post your environment? python version and OS?

Thank you

**Comment by fcurella** [comment]
@joke2k the issue is fixed in master, we just need a new release on PyPI

**Comment by joke2k** [comment]
Wonderful, 
we will wait new year for release new version on PyPi.

**Comment by jeffwidman** [comment]
@joke2k Any chance of pushing a new release?

**Comment by kdeldycke** [comment]
@joke2k : new year was 2 months ago. Any chance for a release? :grimacing:

**Comment by joke2k** [comment]
@fcurella @jeffwidman @kdeldycke et voilà!
https://pypi.python.org/pypi/fake-factory/

**Comment by fcurella** [comment]
:cake:

**Comment by jeffwidman** [comment]
:+1:

**Comment by kdeldycke** [comment]
Fantastic! :+1:
