### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by anantauprety** [joke2k/faker#321]
I am new to this but, I was trying to run tests using: 

~/workspace/mainjoke2k/faker/faker/tests/mymodule (master) $ python -m unittest en_US

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "en_US/__init__.py", line 2, in <module>
    from faker.providers import BaseProvider
ImportError: No module named faker.providers

Is there something I need to do? I also tried running other tests with similar errors:

~/workspace/faker/faker/tests (master) $ python -m unittest en_GB

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "en_GB/__init__.py", line 8, in <module>
    from faker import Factory
ImportError: No module named faker

Could someone show me how to run the tests? I think I am missing something simple.

**Comment by fcurella** [comment]
hi @anantauprety 

My guess is that the `faker` module is not available to the Python path.

The recommended way to run then tests is to run `python setup.py test` from the root of the repo

**Comment by anantauprety** [comment]
Thanks. Will do. New to all this. If I want to add address to ne_NP should I create an issue as well. I think I have the code. Just need to run the tests and commit.

**Comment by fcurella** [comment]
@anantauprety You can create a Pull Request whenever you're ready.

Thank you very much for contributing!

**Comment by anantauprety** [comment]
I am still unable to run the tests. 
I cloned the repository as is and tried running the following command but, I get attribute error:
           AttributeError: 'module' object has no attribute 'zh_CN'

Am I the only one getting this because of the system I have or I am still not running it correctly?
I am however, to build the it fine with python setup.py build. Thanks in advance.

anantauprety:~/workspace/joke2k/faker (master) $ python setup.py test
running test
Searching for python-dateutil>=2.4
Best match: python-dateutil 2.4.2
Processing python_dateutil-2.4.2-py2.7.egg

Using /home/ubuntu/workspace/joke2k/faker/python_dateutil-2.4.2-py2.7.egg
running egg_info
writing requirements to fake_factory.egg-info/requires.txt
writing fake_factory.egg-info/PKG-INFO
writing top-level names to fake_factory.egg-info/top_level.txt
writing dependency_links to fake_factory.egg-info/dependency_links.txt
writing entry points to fake_factory.egg-info/entry_points.txt
reading manifest file 'fake_factory.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.md'
writing manifest file 'fake_factory.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    ':python_version=="3.0"': ['importlib'],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'zh_CN'

**Comment by fcurella** [comment]
hi @anantauprety ,

have you installed the test requirements in `faker/tests/requirements.txt`?

You may also want to take a look at the `.travis.yml` file that's used by our Continous Integration to run the tests, and try following the same steps. Hope that helps
