### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by jonzsi** [joke2k/faker#426]
Any ideas why i am getting ImportError when trying to use Faker? Blow is the error dump.

```
Traceback (most recent call last):
  File "api.py", line 4, in <module>
    from faker import Faker
  File "/Library/Python/2.7/site-packages/faker/__init__.py", line 4, in <module>
    from faker.factory import Factory
  File "/Library/Python/2.7/site-packages/faker/factory.py", line 10, in <module>
    from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
  File "/Library/Python/2.7/site-packages/faker/config.py", line 13, in <module>
    AVAILABLE_LOCALES = find_available_locales(PROVIDERS)
  File "/Library/Python/2.7/site-packages/faker/utils/loading.py", line 19, in find_available_locales
    provider_module = import_module(provider_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/faker/providers/address/__init__.py", line 6, in <module>
    from .. import date_time
  File "/Library/Python/2.7/site-packages/faker/providers/date_time/__init__.py", line 10, in <module>
    from dateutil.tz import tzlocal
  File "/Library/Python/2.7/site-packages/dateutil/tz/__init__.py", line 1, in <module>
    from .tz import *
  File "/Library/Python/2.7/site-packages/dateutil/tz/tz.py", line 23, in <module>
    from ._common import tzname_in_python2, _tzinfo, _total_seconds
  File "/Library/Python/2.7/site-packages/dateutil/tz/_common.py", line 2, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

**Comment by fcurella** [comment]
Hi @jonzsi ,

sorry for the late reply. Is this still happening?

**Comment by jonzsi** [comment]
No, seems to work.
