### ISSUE TITLE
Problems running tests

### ISSUE THREAD

**Issue by brianmay** [joke2k/faker#547]
According to the ``README.rst`` this should work:

```
brian@prune:~/debian/python-modules/faker$ python -m unittest -v tests

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

It doesn't. Also this should work:

```
brian@prune:~/debian/python-modules/faker$ python setup.py test

...

Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    'ipaddress',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 234, in run_tests
    **exit_kwarg
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'internet'
E: pybuild pybuild:283: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
```

EDIT: Sorry, I need to wake up. Edited back original report.

**Comment by brianmay** [comment]
That second error might actually be my fault, I may not have ``email_validator`` installed. Will confirm when I am more awake and have slightly more time:

```
>>> import tests.providers.internet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tests/providers/internet.py", line 7, in <module>
    from email_validator import validate_email
ImportError: No module named email_validator
```

**Comment by joke2k** [comment]
Hi @brianmay,
to solve the second error you have to install the `tests/requirements.txt` in your virtualenv.

I can't reproduce the first one. Probably installing the requirements.txt it will resolve..

**Comment by brianmay** [comment]
I will continue to investigate the first one from my end. Will close this ticket for now.
