### ISSUE TITLE
AttributeError: module 'faker.providers.en_US' has no attribute 'Provider'

### ISSUE THREAD

**Issue by VanDavv** [joke2k/faker#556]
I started using faker in my project in python 3.6 and it works fine.
Problem is, when I want to use it from python console, here's my log:
```
$ python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Faker
>>> fake = Faker()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vandavv/dev/libs/miniconda3/envs/sps/lib/python3.6/site-packages/faker/factory.py", line 38, in create
    prov_cls, lang_found = cls._get_provider_class(prov_name, locale)
  File "/home/vandavv/dev/libs/miniconda3/envs/sps/lib/python3.6/site-packages/faker/factory.py", line 49, in _get_provider_class
    provider_class = cls._find_provider_class(provider, locale)
  File "/home/vandavv/dev/libs/miniconda3/envs/sps/lib/python3.6/site-packages/faker/factory.py", line 87, in _find_provider_class
    return provider_module.Provider
AttributeError: module 'faker.providers.en_US' has no attribute 'Provider'
```
pip freeze shows that I have `Faker==0.7.17`. I'm using running on python `3.6.1` in `Ubuntu 17.04`

**Comment by fcurella** [comment]
Hi @VanDavv , I've tested using a container with Ubuntu 17.04 and python 3.6.1 and it's working for me. What are your locale settings?

**Comment by VanDavv** [comment]
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

**Comment by VanDavv** [comment]
@fcurella It also works for me on docker, but I want to run my code without it

**Comment by fcurella** [comment]
@VanDavv I'm having trouble reproducing this issue. Can you check if it's still happening on the new `0.7.18` release?

**Comment by VanDavv** [comment]
@fcurella nope, `0.7.18` fixed this issue, thanks ;)
