### ISSUE TITLE
AttributeError: module 'faker.providers' has no attribute '__file__'

### ISSUE THREAD

**Issue by narendranani** [joke2k/faker#569]
I converted my python code to .exe using cx_Freeze. While opening my .exe file I am getting this error.

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Program Files\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "DataGenerator.py", line 7, in <module>
  File "C:\Program Files\Python36\lib\site-packages\faker\__init__.py", line 4, in <module>
    from faker.factory import Factory
  File "C:\Program Files\Python36\lib\site-packages\faker\factory.py", line 10, in <module>
    from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
  File "C:\Program Files\Python36\lib\site-packages\faker\config.py", line 11, in <module>
    PROVIDERS = find_available_providers([import_module(path) for path in META_PROVIDERS_MODULES])
  File "C:\Program Files\Python36\lib\site-packages\faker\utils\loading.py", line 29, in find_available_providers
    providers = ['.'.join([providers_mod.__package__, mod]) for mod in list_module(providers_mod)]
  File "C:\Program Files\Python36\lib\site-packages\faker\utils\loading.py", line 7, in list_module
    path = os.path.dirname(module.__file__)
AttributeError: module 'faker.providers' has no attribute '__file__'

**Comment by fcurella** [comment]
Hi @narendranani 

Can you try the `freeze` branch (https://github.com/joke2k/faker/tree/freeze) and tell me if the fix in there is working?

**Comment by narendranani** [comment]
Hi @fcurella 

Thank you for quick response and sorry I didn't get you that what and where I have implement that logic.
