### ISSUE TITLE
Installing on macOS High Sierra

### ISSUE THREAD

**Issue by tushariyer** [joke2k/faker#633]
Running `pip install Faker` results in the following:
```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil', '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil', "[Errno 1] Operation not permitted: '/var/folders/jw/qq2bcv_s0tg2m739gv7dyy0r0000gn/T/pip-6LQqxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil'")]
```

**Comment by fcurella** [comment]
hi @tushariyer 

From the stacktrace, looks like a permission issue on your system. I don't recommend installing on the system Python, and I'd suggest using `virtualenv`. But if you have to, check the permissions of `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python` nad make sure it's writable by your current user.

**Comment by tushariyer** [comment]
That did the trick! Thank you so much!
