### ISSUE TITLE
Import Faker - no module

### ISSUE THREAD

**Issue by quintendewilde** [joke2k/faker#665]
When I run following:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import Faker
ImportError: No module named Faker
```
command line usage gives me correct response

```
faker address
47024 Richards Crossing
Port Leslieburgh, PA 80483
```

which python = /usr/bin/python
I did install pip with brew? Could this be a path problem? And what can I do about it ?

**Comment by Jafnee** [comment]
faker should be lower case.

```
import faker
```

If you meant to import the class `Faker`, it should be

```
from faker import Faker
```

**Comment by swaroop-m** [comment]
I got a similar error (I used faker in lower case only)

```
 File "demo.py", line 1, in <module>
     from faker import Faker
ImportError: No module named faker
```
I got that error and thought I didn't have faker, tried to install faker,
```
 pip install faker
Requirement already satisfied: faker in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (2.0.0)
Requirement already satisfied: six>=1.10 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (1.12.0)
Requirement already satisfied: python-dateutil>=2.4 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (2.8.0)
Requirement already satisfied: text-unidecode==1.2 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (1.2)
```
It was already there, but still the same error.
