### ISSUE TITLE
`faker.utils` missing from latest release

### ISSUE THREAD

**Issue by relwell** [joke2k/faker#724]
```bash
$ pipenv run python3
Python 3.6.4 (default, Mar  9 2018, 23:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/relwell/.local/share/virtualenvs/afterdarkr-4y1ql4D_/lib/python3.6/site-packages/faker/__init__.py", line 4, in <module>
    from faker.factory import Factory
  File "/Users/relwell/.local/share/virtualenvs/afterdarkr-4y1ql4D_/lib/python3.6/site-packages/faker/factory.py", line 10, in <module>
    from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
  File "/Users/relwell/.local/share/virtualenvs/afterdarkr-4y1ql4D_/lib/python3.6/site-packages/faker/config.py", line 3, in <module>
    from faker.utils.loading import find_available_locales, find_available_providers
ModuleNotFoundError: No module named 'faker.utils'
```

I've validated that this is running the latest version of faker, released today.

**Comment by fcurella** [comment]
I just tried, but I can't reproduce the issue.

I've run:

```
$ pipenv --python 3.6
Creating a virtualenv for this project…
Using /Users/flavio/.pyenv/shims/python3.6m to create virtualenv…
⠋Running virtualenv with interpreter /Users/flavio/.pyenv/shims/python3.6m
Using base prefix '/Users/flavio/.pyenv/versions/3.6.2'
New python executable in /Users/flavio/Envs/working_copies-MWxMSUV1/bin/python3.6m
Also creating executable in /Users/flavio/Envs/working_copies-MWxMSUV1/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/flavio/Envs/working_copies-MWxMSUV1     
$ pipenv install faker
Installing faker…
Collecting faker
  Using cached Faker-0.8.12-py2.py3-none-any.whl
Collecting text-unidecode (from faker)
  Using cached text_unidecode-1.2-py2.py3-none-any.whl
Collecting python-dateutil>=2.4 (from faker)
  Using cached python_dateutil-2.7.0-py2.py3-none-any.whl
Collecting six (from faker)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: text-unidecode, six, python-dateutil, faker
Successfully installed faker-0.8.12 python-dateutil-2.7.0 six-1.11.0 text-unidecode-1.2

Adding faker to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (2883c8)!

$ pipenv run python3
Python 3.6.2 (default, Jan  4 2018, 16:14:20) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
>>> 

```
