### ISSUE TITLE
Commandline faker can't import community providers

### ISSUE THREAD

**Issue by crd** [joke2k/faker#804]
See below, where I try to invoke `foo` from `mymodule` included with tests here: https://github.com/joke2k/faker/tree/master/tests/mymodule

### Steps to reproduce

```bash
$ faker --version
faker 0.9.0
$ cd workspaces/contrib/faker
$ ls tests/mymodule/en_US
__init__.py
$ faker foo -i tests.mymodule.en_US
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.6.6/bin/faker", line 11, in <module>
    load_entry_point('Faker==0.9.0', 'console_scripts', 'faker')()
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/cli.py", line 282, in execute_from_command_line
    command.execute()
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/cli.py", line 264, in execute
    includes=arguments.include
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/cli.py", line 71, in print_doc
    fake = Faker(locale=lang, includes=includes)
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/factory.py", line 58, in create
    prov_cls, lang_found = cls._get_provider_class(prov_name, locale)
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/factory.py", line 69, in _get_provider_class
    provider_class = cls._find_provider_class(provider, locale)
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/Faker-0.9.0-py3.6.egg/faker/factory.py", line 92, in _find_provider_class
    provider_module = import_module(provider_path)
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests'
```

### Expected behavior

`foo` from the external module `mymodule` should be invoked.

### Actual behavior

`ModuleNotFoundError`

While I'm at it, I should call out that the mechanism for providing a path to the module to be imported (path delimited with periods) is very weird. While refactoring this I'd recommend updating the command as `-i path/to/module/directory/`

**Comment by fcurella** [comment]
The idea is that you're importing a Python module, not necessarily a directory from the filesystem.

I suspect `workspaces/contrib/faker` is not in your `PYTHONPATH`. Try importing the provider from the Python REPL. If Pyton can't import it, neither can Faker:

```
$ cd workspaces/contrib/faker
$ python
>>> from tests.mymodule.en_US import Provider
```

**Comment by crd** [comment]
Works fine:

```
$ python
Python 3.6.6 (default, Aug 15 2018, 19:08:52)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Faker
>>> from tests.mymodule.en_US import Provider
>>>
```

This is a contrived example, I'm using `mymodule` just to illustrate the larger issue which is the commandline faker tool doesn't seem to be able to use community providers.

``` $ pipenv init
Creating a virtualenv for this project...
...
$ pipenv install faker
Installing faker...
...
$ pipenv install faker-wifi-essid
Installing faker-wifi-essid...
...
$ pipenv shell
...
[venv] $ faker -i faker-wifi-essid
Traceback (most recent call last):
...
ModuleNotFoundError: No module named 'faker-wifi-essid'
```

**Comment by crd** [comment]
Is there another way I should be leveraging the `-i` parameter?

**Comment by fcurella** [comment]
@crd There are two issues at people here:

1) Your provider's class name must be `Provider`, but I noticed this is not mentioned in the docs. I'll make a PR to update the docs
2) You must specify the _import_ path of the module containing the provider class. In you specific case, this would be `$ faker -i faker_wifi_essid` (not the underscores instead of the hyphens).

**Comment by fcurella** [comment]
Reopening awaiting verification by OP

**Comment by crd** [comment]
This works, thanks.

Requiring community providers to name things in this way feels clunky. Is there a better way for python users to leverage my provider than to do this going forward?

```
from faker_credit_score import Provider as CreditScore
...
fake.add_provider(CreditScore)
```

**Comment by fcurella** [comment]
I agree the requirement feels clunky, but I think allowing any class name would require an even clunkier implementation. Instead of just accessing [the attribute](https://github.com/joke2k/faker/blob/master/faker/factory.py#L131), we'd have to iterate over the module's content, and for every name, check for subclasses of `BaseProvider`. And then we would end up with a list.

Something you could do is aliasing your provider. Something like:

```python
class CreditScore(BaseProvider):
    # ....


Provider = CreditScore
```

**Comment by crd** [comment]
:smacks forehead:

Of course. Thanks @fcurella.
