### ISSUE TITLE
Method .vat_id() is not working as documented

### ISSUE THREAD

**Issue by mindflayer** [joke2k/faker#864]
As I mentiond in the title, `.vat_id()` is not working properly

What I get from the lib:
```>>> import faker
>>> f = faker.Faker(locale='it_IT')
>>> f.vat_id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'vat_id'
>>> f = faker.Faker(locale='en_GB')
>>> f.vat_id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'vat_id'
```

What the documentation says:
```
# https://faker.readthedocs.io/en/latest/locales/it_IT.html#faker-providers-ssn
fake.vat_id()
# 'IT32863982442'
# https://faker.readthedocs.io/en/latest/locales/en_GB.html#faker-providers-ssn
fake.vat_id()
# 'GBHA571'
```

**Comment by fcurella** [comment]
Hi @mindflayer 

The `vat_id` method is only available on master, and hasn't been released to PyPI yet.

The issue is that the PyPI page points to the `latest` docs, when it should be pointing to `stable`: https://faker.readthedocs.io/en/stable/locales/it_IT.html#faker-providers-ssn.
